import Head from 'next/head'
import { getData } from '../util/api'

export const getStaticProps = async () => {
  const data = await getData()

  return {
    props: {
      products: data,
    }
  }
}

export default function Home({ products }) {
  console.log(products)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
        {
          products.map(product => (
              <li key = { product.id }>
                <figure>
                <img src = { product.images[0].src }/>
                  <figcaption>{ product.title }</figcaption>
                </figure>
              </li>
          ))
        }
        </ul>
      </main>

      <footer>
      </footer>
      <style jsx>{`
        img {
          width: 100px;
        }
      `}</style>
    </div>
  )
}
